# Generated by Django 4.2.6 on 2023-10-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='phone',
            field=models.CharField(default='09121765555', max_length=11, null=True),
        ),
    ]
