# Generated by Django 4.2.6 on 2023-10-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
