# Generated by Django 4.2.6 on 2023-10-28 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.localtime)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.localtime)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gnames.competition')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('firs_name', 'firs_name'), ('last_name', 'last_name'), ('city', 'city'), ('country', 'country'), ('animal', 'animal'), ('color', 'color')], max_length=20, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.IntegerField(null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.localtime)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gnames.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
