# Generated by Django 4.2.6 on 2023-10-30 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gnames', '0002_rename_word_competition_alphabet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='type',
            field=models.CharField(choices=[('first_name', 'first_name'), ('last_name', 'last_name'), ('city', 'city'), ('country', 'country'), ('animal', 'animal'), ('color', 'color')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('type', 'player', 'competition')},
        ),
    ]
